title: title
page-top-title: Xu, Jiaming
top-section-bg-text: Be what you wanna be
home-subtitle: JimmyXu&ensp;|&ensp;Flashfire1001
copyright-text: '&copy; flashfire1001 2023-2025. All Rights Reserved.'
